### ISSUE TITLE
DIGITALTWIN - Deploy first version of the website

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/www_threefold_twin#15]
We need websites https://github.com/threefoldfoundation/www_threefold_twin to www.twin.threefold.io
and this one https://github.com/threefoldfoundation/info_digitaltwin to wiki.twin.threefold.io

**Comment by Vilnite** [comment]
Isn't this issue
https://github.com/threefoldfoundation/www_threefold_twin/issues/8 '+ https://github.com/threefoldfoundation/www_threefold_twin/issues/9 ?

**Comment by nbabenko** [comment]
waiting for the publishtools - they are not ready yet

**Comment by nbabenko** [comment]
for now it works locally

publishtools pull -r twin
publishtools develop -r twin

**Comment by maximilianrang** [comment]
Publishing is still blocked, but verification via running locally is possible.

**Comment by nbabenko** [comment]
waiting for the web team to publish it
