### ISSUE TITLE
DIGITALTWIN - Publish and integrate wiki to the website

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/www_threefold_twin#19]

**Comment by nbabenko** [comment]
Hi all, 

✅ Our website and wiki deployed:
https://twin.threefold.io/
https://wiki.twin.threefold.io/

⚠️ For now our deployment process will be following:
1. We work in development branches and deploy locally to see the changes
2. When change is finished, we commit to development branch
3. By the end of the week I (or somebody else) have to merge our development branch to master branch
4. On Sunday web team will update production website and wiki using latest version of the master branch. 

📆 Later, when publishing tools will be ready, we will have www2 staging environment and automatic deployment once commit is done to staging environment (development branch) and production (master branch)
I will inform everyone once the process will change for us

**Comment by AlexandreHannelas** [comment]
Wiki good to be linked on the website

**Comment by nbabenko** [comment]
we need a link to the wiki from the website

**Comment by nbabenko** [comment]
link got lost from the website, reopening

**Comment by AlexandreHannelas** [comment]
- Link to the website done
