### ISSUE TITLE
DIGITALTWIN - We need a pitch deck / initial presentation for DT

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/www_threefold_twin#20]

**Comment by nbabenko** [comment]
FairSwap's version of the slides: https://docs.google.com/presentation/d/1zcWiBZfAovpaqZ-SX-amNDxNXOetQWUrk4WRi65Ue1g/edit#slide=id.gb537c02100_0_78

**Comment by AlexandreHannelas** [comment]
Postpone for later (TBC)
