### ISSUE TITLE
DIGITALTWIN - Onboarding Funnel for Reservation 

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/www_threefold_twin#22]
Digital Twin reservation for early adopters

**Comment by nbabenko** [comment]
need to check with jimber guys. Even for the initial phase where we do not share digital twin yet, we need some onboarding funnel and descriptin of the journey.

**Comment by AlexandreHannelas** [comment]
Onboarding funnel doc: https://secure.threefold.me/pad/#/2/pad/edit/ZfDiMb3yvbk4kdXIP3dPxBrC/
Need to get aligned with the Promotion Team

**Comment by AlexandreHannelas** [comment]
Need to progress further in relation to the Payment Provider first. Remove from web 2.8 for now

**Comment by Sacha96** [comment]
hey guys i'm removing my assignment for now as I have 30+ issues in my funnel. bring me back in when its ready for me to go through it.

**Comment by AlexandreHannelas** [comment]
Content made here: https://secure.threefold.me/pad/#/2/pad/edit/ZCWi6wpp6PUAH6JMnVozRl3E/ 
Need to finalize and see if this is possible with development team as per issue: https://github.com/threefoldfoundation/www_threefold_twin/issues/71
