### ISSUE TITLE
DIGITALTWIN - Put main website behind TF Connect authentication

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/www_threefold_twin#25]
We need to publish website https://github.com/threefoldfoundation/www_threefold_twin to www.twin.threefold.io
and this one https://github.com/threefoldfoundation/info_digitaltwin to wiki.twin.threefold.io

**Comment by nbabenko** [comment]
Found out that Hamdy is probably the best person to help with this, checking details with him currently

**Comment by nbabenko** [comment]
publishtools and tfconnect is not ready yet, waiting for update from the web team

**Comment by nbabenko** [comment]
Kristine told that this should be ready by the end of this week (March 7th)

**Comment by Vilnite** [comment]
The website is live on https://twin.threefold.io/
wiki will be pushed live as soon as we have prefixes set up.

As per TF Connect authentication, that we need to set for a bit later after prefixes are in place, so I'm moving this issue to To Do on web_2.5.4 for now.

**Comment by AlexandreHannelas** [comment]
Push to later. For now, we are closing this issue
