### ISSUE TITLE
DIGITALTWIN - Update public landing page

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/www_threefold_twin#26]
![photo_2021-02-25_09-43-49](https://user-images.githubusercontent.com/4426772/109124326-7858ab80-7753-11eb-864d-29e204de6b6d.jpg)
Landing page should be according this mockup

**Comment by maximilianrang** [comment]
Please note that this public landing page should not have the menu items "PRICES" and "GITHUB"

**Comment by Vilnite** [comment]
For now, can be viewed locally : http://localhost:8080/landing
