### ISSUE TITLE
DIGITALTWIN  - Write first set of blog articles

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/www_threefold_twin#3]
Write down first set of blog articles:
- [x] When service is free you are the product
- [ ] Digital pandemic (Sam wrote an article on this btw – draft here)
- [ ] Peer-2-peer encrypted interaction
- [ ] How big players abuse data to their advantage (Hedge Funds etc)
- [x] Select FinTwin articles that can be related to DT and can be published with DT release

**Comment by AlexandreHannelas** [comment]
Blog articles:
- Actually, you are the product - need review
https://secure.threefold.me/pad/#/2/pad/edit/korh19b8gSY+Px21qUkVvc0i/
- Why should you care? - need review 
https://secure.threefold.me/pad/#/2/pad/edit/FqJh27Qkfrzt-3JAvqqUSPRO/
- Better understanding of wealth 

in folder
