### ISSUE TITLE
DIGITALTWIN - Define first version of the pricing and offer

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/www_threefold_twin#4]
Define what exactly are we bringing to the user for their lifetime payment. What exactly will be "Lifetime Free"? 
Define fee structure and business model, what are the limitation of the usage (capacity limitation, amount of users on a call, etc). 
Define costs for users, - what is the regular use from people and how much it will cost for us, we should understand value proposition ourselves and explain it to people
Split lifetime package 50/50 between service fee and capacity fee and then explain how long will it last in normal usage conditions
Explain in simple terms how much capacity is needed for certain use-cases and how much it costs and present bundled packages for capacity plans
Define invite only model

**Comment by nbabenko** [comment]
We offer only 100 USD lifetime package for now, with no capacity included. We have to describe it in the wiki

**Comment by maximilianrang** [comment]
Moved to done because the definition of the 100 USD package has been approved and is ready for implementation.
