### ISSUE TITLE
DigitalTwin website - How DT is the next evolution of privacy and freedom 

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/www_threefold_twin#41]
Sam: Also want to add something to the home page that emphasizes "all in one place."

**Comment by samtaggart** [comment]
@AlexandreHannelas Why did you close this? Duplicate?

**Comment by AlexandreHannelas** [comment]
Yes duplicate: https://github.com/threefoldfoundation/home/issues/127
