### ISSUE TITLE
DigitalTwin - "Hidden Costs of Data Manipulation" - Replace Horizontal Info Graphic with Vertical Version for Mobile version 

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/www_threefold_twin#47]

**Comment by AlexandreHannelas** [comment]
AI file sent to @Vilnite

**Comment by Vilnite** [comment]
Please update roadmap's css:

<img width="1219" alt="Screenshot 2021-03-18 at 13 39 25" src="https://user-images.githubusercontent.com/20182572/111620492-797b7680-87ef-11eb-84f8-cb2387906712.png">

as close to this as possible:

<img width="342" alt="Screenshot 2021-03-18 at 13 40 48" src="https://user-images.githubusercontent.com/20182572/111620568-90ba6400-87ef-11eb-995e-7ba2970a71b2.png">

- [ ] Remove blocks from text
- [ ] Background colour #FCFFE3
- [ ] remove numbers from circles and gradually change color for each circle
> - [ ] 1 = #FF7697
> - [ ] 2 = #FFA3B2
> - [ ] 3 = #FFC3CD
> - [ ] 4 = #FFE3E7
> - [ ] 5 = #FFF4F7

**Comment by ehab-hassan** [comment]
while we use image at road map desktop I use the horizontal one for mobile as image also see if that work with u

**Comment by Vilnite** [comment]
works :)
