### ISSUE TITLE
DigitalTwin - New logos of each experience 

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/www_threefold_twin#48]

**Comment by AlexandreHannelas** [comment]
AI file sent to @Vilnite

**Comment by Vilnite** [comment]
Please make each app clickable, will add a link for each that will open a new page within website:

<img width="1315" alt="Screenshot 2021-03-18 at 14 07 10" src="https://user-images.githubusercontent.com/20182572/111623595-3de2ab80-87f3-11eb-8aec-99df4009f70b.png">

**Comment by ehab-hassan** [comment]
done at development
