### ISSUE TITLE
DIGITALTWIN - Define Target Audiences

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_threefold_twin#5]
We need a clear understanding of who we are addressing with our Digital Twin offer.

So far we agreed that the core product is consumer-facing and not for tech enthusiasts only:
- clear, non-technical language
- accounting for a short attention span
- bold messaging
- the simpler the product structure, the more adoption
For language and messaging, we will stay close to terminologies used in "The Great Hack" and "Social Dilemma", because those documentaries are directed exactly at our audience and reach them successfully.

The secondary audiences are corporations and governments for our enterprise solution:
- needs to be explored

**Comment by Vilnite** [comment]
When move to done, please also close the issue.
