### ISSUE TITLE
DigitalTwin - Wiki set for review (locally)

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/www_threefold_twin#51]
DT wiki is ready. Please check. I added **p2p page** between Vision and Experience.

md file name: power_of_p2p.md

this will follow https://github.com/threefoldfoundation/home/issues/127 direction of bringing more p2p forward

**Comment by Sacha96** [comment]
I went through it this week and it looks good to me. I will go through it through it and make a few changes with @AlexandreHannelas to tackle threefoldfoundation/info_digitaltwin#15 this week.
