### ISSUE TITLE
DIGITALTWIN: Look at CTAs

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_twin#53]
Make sure enough CTAs and proper ones and links to wikis and blog articles with more info and about the why.

Related to Digital Twin for Life additions.

**Comment by samtaggart** [comment]
Talked with @Sacha96 this needs to be done this week before Thursday.

**Comment by Sacha96** [comment]
For now it seems there is no applicable call to actions for DT. I'm moving it to next.

**Comment by Sacha96** [comment]
3. What would be the call to action until product is ready? This needs to be defined by DT Team. 

Once these are figured out. We can bring that issue to priorities.

**Comment by Sacha96** [comment]
removed priority major as just called with @AlexandreHannelas. 

1. Can't reserve/ pay for a DT yet
2. Maybe we can do a group for DT that is separate from TF's Telegram/ Discourse?
3. What would be the call to action until product is ready? This needs to be defined by DT Team. 

Once these are figured out. We can bring that issue to priorities.
