### ISSUE TITLE
Digital Twin: Add navigation buttons to each experience page

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_twin#56]
Please add navigation buttons at the bottom of each digital twin experience page (see below for visual):

- [x] On Chat, button 1 should be Social and button 2 should be Meet
- [x] On Meet, button 1 should be Chat and button 2 should be File Storage
- [x] On File Storage, button 1 should be Meet and button 2 should be Office
- [x] On Office, button 1 should be File Storage and button 2 should be Web Publisher
- [x] On Web Publisher, button 1 should be Office and button 2 should be Payments
- [x] On Payments, button 1 should be Web Publisher and button 2 should be Network
- [x] On Network, button 1 should be Payments and button 2 should be Social
- [x] On Social, button 1 should be Network and button 2 should be Chat

<img width="1088" alt="Screen Shot 2021-03-21 at 8 30 42 PM" src="https://user-images.githubusercontent.com/50134479/111914774-8664c800-8a84-11eb-9c13-f96cafe1b180.png">

**Comment by AlexandreHannelas** [comment]
Wait to receive mock-up for the two new experiences to be added to Digital Twin Applications on Home Page: #70
