### ISSUE TITLE
TWIN: (LATER) Add Communication Channels when ready

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_twin#58]
Once we have communication channels specifically for Twin, we need to add them to header & footer.

**Comment by AlexandreHannelas** [comment]
Telegram Channel - Digital Twin News & Updates has been created. 
Needs to be added to DT Website as per https://github.com/threefoldfoundation/www_threefold_twin/issues/57

DT Forum and other platforms profiles still need to be created
