### ISSUE TITLE
TWIN: Metadata needs to be updated

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_twin#59]
- Digital Twin | Own Your Data
- The Digital Twin assures that only you own your data, and no one else. Access numerous applications while forever remaining fully secure and private.
- Image: Use image from header

Let me know if something else is needed.

<img width="517" alt="Screen Shot 2021-03-22 at 4 31 55 PM" src="https://user-images.githubusercontent.com/50134479/111997686-5670ff80-8b2c-11eb-9fc7-de3c40d808ab.png">

**Comment by samaradel** [comment]
image is already there and the title will update next merge

![image](https://user-images.githubusercontent.com/11662805/112465493-793e2680-8d6d-11eb-8e61-072f6662b113.png)

**Comment by samtaggart** [comment]
Great thank you!
