### ISSUE TITLE
DigitalTwin: Integrate Liquid Quick Exchange on DT Website 

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/www_threefold_twin#62]
Integrate Liquid Quick Exchange to accept payment in TFT

**Comment by nbabenko** [comment]
Beta version is implemented. 
Test branch: https://github.com/threefoldfoundation/www_threefold_twin/tree/liquid-quick-exchange-widget-test

Workflow: https://docs.google.com/document/d/1MqNAAEwA9i4W9V4d2oFMNJWqHBOXgoEzfTtVjDw54fo/edit#

Need feedback from stakeholders if we should proceed with it or no.

**Comment by AlexandreHannelas** [comment]
Closed it for now, will not be implemented on the website -> Decision after stakeholder call
