### ISSUE TITLE
DigitalTwin: Experience/Chat - Missing one part of the headphone

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/www_threefold_twin#64]
<img width="507" alt="Screen Shot 2021-04-04 at 8 48 54 PM" src="https://user-images.githubusercontent.com/78421574/113515956-ec1e7d00-9577-11eb-8790-08cc5c5b5250.png">

Missing one part of the Headphone 

From AI File sent to @Vilnite 
![REF FILE KV - DT Features - Chat](https://user-images.githubusercontent.com/78421574/113516021-4ddee700-9578-11eb-9779-6c71727f01a4.png)

**Comment by Vilnite** [comment]
<img width="851" alt="Screenshot 2021-04-07 at 13 40 59" src="https://user-images.githubusercontent.com/20182572/113853905-e78bdb80-97a6-11eb-8ef4-4d12b0059511.png">

**Comment by AlexandreHannelas** [comment]
Done: Verified on Local
