### ISSUE TITLE
DT > Remove tlegram of TF

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_twin#67]
There are call to actions leading to threefold. remove before Thursday 9th please as we are negotiating with payment provider and no association should be made in public eye with casper announcement.
<img width="1213" alt="Screenshot 2021-04-05 at 19 22 04" src="https://user-images.githubusercontent.com/54844940/113597331-d5d9f500-963b-11eb-8c66-52df85963757.png">

**Comment by AlexandreHannelas** [comment]
Link to new Digital Twin Telegram Channel: https://t.me/joinchat/JnJfqY9tfAU1NTY0
