### ISSUE TITLE
DIGITALTWIN - create a forum

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_twin#68]
Please create a separate forum for Digital Twin.
Check for Domain with @AlexandreHannelas 

Ping me when done, I'll update links (currently linking to TF Forum / Digital Twin category)

**Comment by VonSub** [comment]
@Pishoy can we get a second forum instance running for Digital Twin?

- start with staging only first so we can fill it up. forum2.mydigitaltwin.io
- prepare a production environment as well forum.mydigitaltwin.io

**Comment by hossnys** [comment]
here is the staging forum https://forum2.mydigitaltwin.io  , @VonSub  invitation sent for you as moderator so you can invite more people.

**Comment by hossnys** [comment]
here is the production forum https://forum.mydigitaltwin.io , @VonSub invitation sent for you as moderator.

**Comment by VonSub** [comment]
perfect, thanks!
