### ISSUE TITLE
DigitalTwin: Add universe and update header and footer

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/www_threefold_twin#69]
Universe will lead to Threefold as Digital Twin is now part of Threefold Ecosystem

**Comment by Sacha96** [comment]
header:
- Universe
   - ThreeFold
   - ThreeFold Token
   - ThreeFold Grid
   - P2P Cloud
   - P2P Marketplace
   - Digital Twin 
   - Conscious Internet
   - ThreeFold Tech 
- Why ---> Zia should have provided p2p page and we link to that one.
- Experiences 
- Participate 
   - Digital Twin For Life 
   - Buy TFT (https://mydigitaltwin.io/info/twin#/twin__how_to_get_tft)
   - Get Started (https://mydigitaltwin.io/info/twin#/twin__getting_started)
- Learn
   - What is Digital Twin? (https://info.mydigitaltwin.io/#/)
   - What is Peer-to-Peer? (https://info.mydigitaltwin.io/#/twin__power_of_p2p)
   - Digital Twin Vision (https://info.mydigitaltwin.io/#/twin__our_vision)
   - Benefits of Digital Twin (https://info.mydigitaltwin.io/#/twin__benefits)
   - Get Started (https://info.mydigitaltwin.io/#/twin__getting_started)
   - Pricing (https://info.mydigitaltwin.io/#/twin__price)
   - About the tech (https://info.mydigitaltwin.io/#/twin__howdoesitwork)
- About us
   - Blog
   - Newsroom
   - Partners
   - Join Community
   - Contact Us

footer:
- Universe
   - ThreeFold
   - ThreeFold Token
   - ThreeFold Grid
   - P2P Cloud
   - P2P Marketplace
   - Digital Twin 
   - Conscious Internet
   - ThreeFold Tech 
- Participate 
   - Digital Twin For Life 
   - Buy TFT (https://mydigitaltwin.io/info/twin#/twin__how_to_get_tft)
   - Get Started (https://mydigitaltwin.io/info/twin#/twin__getting_started)
- Learn
   - What is Digital Twin? (https://info.mydigitaltwin.io/#/)
   - What is Peer-to-Peer? (https://info.mydigitaltwin.io/#/twin__power_of_p2p)
   - Digital Twin Vision (https://info.mydigitaltwin.io/#/twin__our_vision)
   - Benefits of Digital Twin (https://info.mydigitaltwin.io/#/twin__benefits)
   - Get Started (https://info.mydigitaltwin.io/#/twin__getting_started)
   - Pricing (https://info.mydigitaltwin.io/#/twin__price)
   - About the tech (https://info.mydigitaltwin.io/#/twin__howdoesitwork)
- About us 
   - Blog
   - Newsroom
   - Partners
   - Join Community
   - Contact Us
