### ISSUE TITLE
Digital Twin: Add two more Experiences: 1) alternative to Facebook 2) alternative to LinkedIn 

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/www_threefold_twin#70]
Add 2 new experiences for facebook and Linkedin alternative:

See workings down in the doc: https://secure.threefold.me/pad/#/2/pad/edit/NiMhcN6gp+0wnD2jVBTdZDqm/

- [x] Define language (@Sacha96 @samtaggart)
- [x] Pages created by Zia 
- [x] Added to Website (@Vilnite)
- [x] Added to Wiki (@Sacha96 @AlexandreHannelas)

**Comment by AlexandreHannelas** [comment]
File sent to Zia

**Comment by Sacha96** [comment]
@samtaggart & myself reviewed the data and made sure ti was aligned with all conversations we had with kristof before. Let's push

**Comment by AlexandreHannelas** [comment]
File sent by @Zizaster 
![DTF - SOCAsset 21](https://user-images.githubusercontent.com/78421574/115249119-9a095a00-a128-11eb-9af2-4244ca04523c.png)
![DTF - NETAsset 22](https://user-images.githubusercontent.com/78421574/115249147-a097d180-a128-11eb-94e0-086cb7e8c727.png)
![DT - APPSAsset 24](https://user-images.githubusercontent.com/78421574/115249157-a2619500-a128-11eb-918f-8639aa58ac4a.png)

**Comment by AlexandreHannelas** [comment]
AI file sent to @Vilnite
