### ISSUE TITLE
DIGITALTWIN - add Digital Twin for Life page

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_twin#74]
Need to create and add to DT website Digital Twin for Life page.

Provided mockup:
![DTAsset 26](https://user-images.githubusercontent.com/20182572/114390880-7467d800-9b9f-11eb-9c69-eb830b7de2e9.png)

Need confirmation @Sacha96 and @AlexandreHannelas about final mockup and text so I can move it further on development side.

Do we have only this header? 
Where does it link to?

**Comment by Vilnite** [comment]
Please note, this is DT navigation bar:

<img width="1438" alt="Screenshot 2021-04-13 at 13 35 15" src="https://user-images.githubusercontent.com/20182572/114539399-244f4b00-9c5d-11eb-9d14-aa1d8261ca3a.png">

It's white. We can not have it green on one page.
This respectively will affect looks of header being all with green background.

**Note:** cleared by @Zizaster
"You have two options: 

1. Keep background color green and navigation bar white. 
2. Background white also. Developers can do this. 

Up to you guys to proceed with whatever you think is better."

**Comment by Vilnite** [comment]
Also how would you like page to be called? (Showed in navbar?)
Where do we link it/to it?

@Sacha96 @AlexandreHannelas

**Comment by AlexandreHannelas** [comment]
@Vilnite, as discussed there will be more content on the new price page 

Crypt pad for new price page: https://secure.threefold.me/pad/#/2/pad/edit/3kserevCbyyXy4suwO-QzYYw/
Will coordinate with Zia around that

**Comment by Vilnite** [comment]
Ok. Page is added with current information:
<img width="1440" alt="Screenshot 2021-04-14 at 10 55 19" src="https://user-images.githubusercontent.com/20182572/114674554-05f65780-9d10-11eb-97cd-e0966c47f1ee.png">

Please create a new issue when ready for update.
