### ISSUE TITLE
DigitalTwin: Add/Update DT For Life page 

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/www_threefold_twin#75]
<img width="1440" alt="114674554-05f65780-9d10-11eb-97cd-e0966c47f1ee" src="https://user-images.githubusercontent.com/78421574/114875584-ba21dc00-9dfd-11eb-90b0-b2dd55a7cf20.png">

Change text to:

title: A lifetime of digital freedom for just 1000 TFTs

Text: Digital Twin will be available soon. Become an early adopter and one of the first to access a growing number of secure and private applications for life!

Button: Buy TFT >> https://info.mydigitaltwin.io/#/twin__how_to_get_tft

Button: Learn more >> https://info.mydigitaltwin.io/#/twin__get_your_dt_home

**Comment by Vilnite** [comment]
@samaradel can you please add another button to this component?

<img width="1440" alt="Screenshot 2021-04-16 at 15 03 06" src="https://user-images.githubusercontent.com/20182572/115028311-5e268880-9ecd-11eb-8a07-1fd6bba5cfba.png">

Learn More, link: https://info.mydigitaltwin.io/#/twin__get_your_dt_home

P.s. Make sure it doesn't show on other header components IF input is not given.
