### ISSUE TITLE
DigitalTwin: Fix File Storage image typo on home page

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_twin#76]
fles >>> files

@AlexandreHannelas Please coordinate getting this fixed by Sunday.

By the way, this should never happen in the first place. That's on all of us as reviewers.

<img width="347" alt="Screen Shot 2021-04-12 at 4 17 33 PM" src="https://user-images.githubusercontent.com/50134479/115023179-17ce2b00-9ec7-11eb-8e01-d2071c294a31.png">

**Comment by AlexandreHannelas** [comment]
Did a whole website overview. @Vilnite will do the edits. 
Issue: https://github.com/threefoldfoundation/www_threefold_twin/issues/78
