### ISSUE TITLE
Digital Twin: Add Reservation page

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_twin#77]
https://secure.threefold.me/pad/#/2/pad/edit/ZCWi6wpp6PUAH6JMnVozRl3E/

This will replace button buy tft from -> https://github.com/threefoldfoundation/www_threefold_twin/issues/75

Instead on DT For Life page Button Buy TFT we will put button **Reserve DT Now** and link to Reservation page

**Comment by AlexandreHannelas** [comment]
Ai File sent to @Vilnite 

![REF - DT - Updated DT for Life Page](https://user-images.githubusercontent.com/78421574/115374635-51f04300-a1cd-11eb-948f-7c9e6834a15f.png)

**Comment by Vilnite** [comment]
@ehab-hassan , please see how you can re-create the page so it meets the mockup above. 
(ai file sent DM on telegram)
