### ISSUE TITLE
DIGITALTWIN - Website - Setting up Tailwind templates via Gridsome

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/www_threefold_twin#8]
- [x] clone existing gridsome repo
- [x] change templates, menu & structure to the one provided in this document https://secure.threefold.me/pad/#/2/pad/edit/64vtOgQDuyhhwQHALKJDZMLG/

**Comment by Vilnite** [comment]
Gridsome is applied to www_threefold_twin.

Currently we have simple landing page live: https://twin.threefold.io/
To change current template please provide complete mockup with content and images, so we can see what's been aimed for.

Mockup example:
![TFIO WS REF](https://user-images.githubusercontent.com/20182572/108312500-7cb71e80-71bf-11eb-8759-5915a09f8f8b.png)

It doesn't have to be as polished as this, but at least as close to expected end result as possible to avoid miscommunication and guessing.

Example for issue to setup a website:
https://github.com/threefoldfoundation/www_threefold_io/issues/1

**Comment by maximilianrang** [comment]
Content for HOME is probably ready on Wednesday evening.

**Comment by Vilnite** [comment]
Working with latest mockup:
https://xd.adobe.com/view/ecca36aa-3c4b-4fec-9d86-b48bf98881c1-b999/?fullscreen
