### ISSUE TITLE
Digital Twin: Add Partners quote on home page 

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/www_threefold_twin#83]
Add Partners quote on home page of Digital Twin website. 
AI File sent to @Vilnite 

See below
![REF - DT - Updated Partners Section](https://user-images.githubusercontent.com/78421574/115375339-fc686600-a1cd-11eb-84a0-8d5c051b67e9.png)

**Comment by Vilnite** [comment]
For this can we please add a new Testimonials component 
- [x] to DT website (right after partner logos)
- [x] to examplesite (wherever)

https://tailwindui.com/components/marketing/sections/testimonials

<img width="1440" alt="Screenshot 2021-04-20 at 12 48 24" src="https://user-images.githubusercontent.com/20182572/115384058-40179b80-a1df-11eb-992e-69bf0cb132e0.png">

Considering information provided for testimonials block:

- [x] remove purple background
- [x] align css with website's style
- [x] make partner's logo clickable and linking to a specific partners description page
- [x] make person's image (from data_threefold) clickable and linking to a specific persons descriptions page
> - [x] "Through the Digital Twin technology we able to deliver a completely new pathway for farmers, and help them generate and market real impact.", 
Jeroen Douglas, Executive Director, Solidaridad Network _(jeroen_douglas)_
> - [x] "Our peer-to-peer platform will be on the Threefold Grid and will utilize elements of Digital Twin technology. The Video Chat (Meet) solution will be used to allow teachers to teach refugees.",
Keon Timmers, Director, TAG _(koen_timmers)_
