### ISSUE TITLE
Digital Twin: Add roadmap in Reservation page 

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/www_threefold_twin#84]
Add roadmap on DT Reservation page to lead the user to download TF Connect and to Buy TFT

**Comment by AlexandreHannelas** [comment]
AI file sent to @Vilnite with guidelines

**Comment by Vilnite** [comment]
To be added right after existing component on dt_for_life page:

<img width="924" alt="Screenshot 2021-04-23 at 10 47 55" src="https://user-images.githubusercontent.com/20182572/115845710-cc1d0380-a429-11eb-8a76-eccb6d43b054.png">


**Main Title:** How to get Your own Digital Twin
**Sub-title:** Digital Twin will soon be available for Reservation. Follow the process to secure yours!


1. **Title:**  Download the ThreeFold Connect App
**Text:** The ThreeFold Connect is a 2-Step Verification to protect your account with both your password and your phone.
 On top of that, the app provides you with a Digital Wallet to store your digital assets (e.g. TFT's). 
**Button1:** App Store, link: https://apps.apple.com/us/app/3bot-login/id1459845885
**Button2:** Google Play, link: https://play.google.com/store/apps/details?id=org.jimber.threebotlogin&hl=en_US
_if 2 buttons not possible:_
**Button:** Get TF Connect, link: https://info.mydigitaltwin.io/#/twin__threefold_connect


 2. **Title:** Get your TFT's to reserve your Digital Twin for Life
**Text:** You can reserve your Digital Twin for Life for only **1000 TFT's**. If you don’t have TFT's yet, learn more how to buy. 
**Button:** Buy TFT, link: https://info.mydigitaltwin.io/#/twin__how_to_get_tft

 3. **Title:** Reserve Digital Twin for Life 
**Text:** Join our DT Telegram Group to be the first to know when Reservation is activated on TF Connect App.
**Button:** Join Community, https://t.me/joinchat/JnJfqY9tfAU1NTY0

 4. **Title:** Enjoy the benefits of Digital Twin for Life 
**Text:** Digital Twin for Life comes with seamless experiences. Grant yourself and your peers with a lifetime digital freedom. 
**Button:** n/a
