### ISSUE TITLE
convert website to SVELTE

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_twin#87]
# MOVE WEBSITE TO SVELTE

## Purpose

- get knowledge about how to work svelte and tools around
- get to know some of our engineers & tools we use
- a first project to work with our team

## What

- convert gridsome based website to svelte and https://kit.svelte.dev/
- use https://mdsvex.com/ for the markdown content
- make it all easier to develop/use

## requirements

- put all code in github https://github.com/threefoldfoundation/www_threefold_twin
    - ask to get access
    - in branch 'svelte'
- use https://gitpod.io/ to allow anyone starting from the repo start their development env
	- use prebuilds feature
	- run svelte dev server
	- show how easy it is to change website
- make sure its all documented so people can follow what happens & learn from it
- organize it well so its easy for non developers to change content
- menu needs to come from metadata
- work with nice components
- keep on using tailwind 

## More info

- see how we used gitpod ourselves in https://github.com/crystaluniverse/publishtools

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/39
