### ISSUE TITLE
convert website to VUE with VUE templates (remove gridsome)

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_twin#88]
# MOVE WEBSITE TO VUE

## Purpose

- get to know some of our engineers & tools we use
- a first project to work with our team

## What

- convert gridsome based website to vue template based website
- make it all easier to develop/use, no more gridsome (makes it more dynamic)
- data needs to come from backend which gets it from filesystem
- make sure the data/components/web pages/markdown is nicely structured

## requirements

- put all code in github https://github.com/threefoldfoundation/www_threefold_twin
    - ask to get access
    - in branch 'vue'
- use https://gitpod.io/ to allow anyone starting from the repo start their development env
	- use prebuilds feature
	- run dev server
	- show how easy it is to change website
- make sure its all documented so people can follow what happens & learn from it
- organize it well so its easy for non developers to change content
- menu needs to come from metadata
- work with nice components as we do now (vue components)
- keep on using tailwind 

## More info

- see how we used gitpod ourselves in https://github.com/crystaluniverse/publishtools
- see also #1 which is related but not same, we want to choose and see which one is the best approach, we like svelte a lot but maybe its not stable enough yet

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/38
